set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports tx]

set_property PACKAGE_PIN N5 [get_ports rx]
set_property PACKAGE_PIN T4 [get_ports tx]





set_property IOSTANDARD LVCMOS33 [get_ports {mode_selection[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode_selection[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports brake]
set_property IOSTANDARD LVCMOS33 [get_ports turn_right_light]
set_property IOSTANDARD LVCMOS33 [get_ports turn_right]
set_property IOSTANDARD LVCMOS33 [get_ports turn_left_light]
set_property IOSTANDARD LVCMOS33 [get_ports turn_left]
set_property IOSTANDARD LVCMOS33 [get_ports throttle]
set_property IOSTANDARD LVCMOS33 [get_ports reverse_gear]
set_property IOSTANDARD LVCMOS33 [get_ports power_on]
set_property IOSTANDARD LVCMOS33 [get_ports power_off]
set_property IOSTANDARD LVCMOS33 [get_ports clutch]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN T3 [get_ports {mode_selection[1]}]
set_property PACKAGE_PIN T5 [get_ports {mode_selection[0]}]
set_property PACKAGE_PIN P5 [get_ports clutch]
set_property PACKAGE_PIN R11 [get_ports power_on]
set_property PACKAGE_PIN P4 [get_ports brake]
set_property PACKAGE_PIN R15 [get_ports power_off]
